[log]
  # Log level. One of "debug", "info", "warn", "error".
  level = "debug"
  # Log output format. One of "json" or "text".
  format = "text"
  # Include source filenames and line numbers in the log output.
  caller = true

[[notification]]
  # Shoutrrr service url (see https://github.com/containrrr/shoutrrr).
  url = "slack://token:token@channel/"

[[nameserver]]
  provider = "cloudflare"
  # Profile > API Tokens > Create Token
  # The token must have the permission to edit the required zone(s), but nothing else.
  # Do not use the Global API Key!
  credentials = "secret token"
  # List of zones this nameserver is responsible for.
  zones = ["example.com"]

[[domain]]
  # The domain record to update.
  name = "raspberry-pi.example.com"
  # Zone is the zone name matching a configured nameserver.
  zone = "example.com"
  #    A for IPv4
  # AAAA for IPv6
  kind = "AAAA"
  # What network interface to search for an ip on.
  # See `ip address`.
  interface = "eth0"
  # Suffix is optional and used to filter ip candidates based on suffix.
  # The "suffix" is parsed as a full ip but matched by the inversed subnet mask.
  # This is basically the part after the network prefix assigned by the isp.
  suffix = "::1234:1234:1234:1234"
