[log]
  # Log level. One of "debug", "info", "warn", "error".
  level = "debug"
  # Log output format. One of "json" or "text".
  format = "text"
  # Include source filenames and line numbers in the log output.
  caller = true

[[notification]]
  # Shoutrrr service url (see https://github.com/containrrr/shoutrrr).
  url = "slack://token:token@channel/"

[[nameserver]]
  provider = "cloudflare"
  # Profile > API Tokens > Create Token
  # The token must have the permission to edit the required zone(s), but nothing else.
  # Do not use the Global API Key!
  credentials = "${DYNFLARE_CLOUDFLARE_TOKEN}"
  # List of zones this nameserver is responsible for.
  zones = ["example.com"]

[[domain]]
  # The domain record to update.
  name = "raspberry-pi.example.com"
  # Zone is the zone name matching a configured nameserver.
  zone = "example.com"

  filter = """
    Is6() and
    IsInterface("eth0") and
    HasSuffix("::1234:1234:1234:1234") and
    not HasFlag("deprecated")
  """

[[domain.post-up]]
  cmd = "/usr/bin/sh"
  args = [
    "/usr/local/bin/my-custom-script.sh"
  ]
