---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dynflare.fullname" . }}-config
  labels:
    {{- include "dynflare.labels" . | nindent 4 }}
data:
  config.toml: |
    [log]
    level = {{ .Values.dynflare.log.level | quote  }}
    format = "text"
    caller = true
    {{- range $i, $notification := .Values.dynflare.notification }}

    [[notification]]
    url = {{ $i | printf "${DYNFLARE_NOTIFICATION_%d_URL}" | quote }}
    {{- end -}}
    {{- range $i, $nameserver :=  .Values.dynflare.nameserver }}

    [[nameserver]]
    provider = {{ $nameserver.provider | quote }}
    {{- if $nameserver.credentialsSecretRef }}
    credentials = {{ $i | printf "${DYNFLARE_NAMESERVER_%d_CREDENTIALS}" | quote }}
    {{ end -}}
    zones = [
    {{ range $i, $zone := .zones }}
    {{- if $i -}},{{- end -}}
    {{- $zone | quote | indent 2 -}}
    {{ end }}
    ]
    {{ end -}}
    {{- range $domain := .Values.dynflare.domain }}
    [[domain]]
    name = {{ $domain.name | quote }}
    zone = {{ $domain.zone | quote }}
    filter = """
    {{- .filter | nindent 6 -}}
    """
    {{ end -}}

