name: Docker

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'

jobs:
  docker:
    name: Publish docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v3 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - name: Build and Push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/lukasdietrich/dynflare:latest

