name: Docker

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'

jobs:
  docker:
    name: Publish docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Container Tags
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/lukasdietrich/dynflare
          tags: |
            type=edge
            type=semver,pattern={{version}}
            type=sha

      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v3 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - name: Build and Push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
