name: Lint

on:
  push:
    branches:
      - master
    pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  golangci:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          cache: false

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: latest
