name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Build
        run: |
          sudo apt install musl-dev musl-tools

          go build -o dynflare -v ./cmd/dynflare
          CGO_ENABLED=1 CC=musl-gcc go build --ldflags '-linkmode=external -extldflags=-static' -o dynflare.musl -v /cmd/dynflare

      - name: Sha256sum
        run: |
          ls -la
          sha256sum dynflare > dynflare.sha256sum
          sha256sum dynflare.musl > dynflare.musl.sha256sum
          sha256sum --check *.sha256sum

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            LICENSE
            dynflare
            dynflare.sha256sum
            dynflare.musl
            dynflare.musl.sha256sum

